// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageHeadProto.proto

#ifndef PROTOBUF_MessageHeadProto_2eproto__INCLUDED
#define PROTOBUF_MessageHeadProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_MessageHeadProto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMessageHeadImpl();
void InitDefaultsMessageHead();
inline void InitDefaults() {
  InitDefaultsMessageHead();
}
}  // namespace protobuf_MessageHeadProto_2eproto
namespace WZRY {
class MessageHead;
class MessageHeadDefaultTypeInternal;
extern MessageHeadDefaultTypeInternal _MessageHead_default_instance_;
}  // namespace WZRY
namespace WZRY {

// ===================================================================

class MessageHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WZRY.MessageHead) */ {
 public:
  MessageHead();
  virtual ~MessageHead();

  MessageHead(const MessageHead& from);

  inline MessageHead& operator=(const MessageHead& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageHead(MessageHead&& from) noexcept
    : MessageHead() {
    *this = ::std::move(from);
  }

  inline MessageHead& operator=(MessageHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageHead* internal_default_instance() {
    return reinterpret_cast<const MessageHead*>(
               &_MessageHead_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MessageHead* other);
  friend void swap(MessageHead& a, MessageHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageHead* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageHead* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageHead& from);
  void MergeFrom(const MessageHead& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 len = 1;
  bool has_len() const;
  void clear_len();
  static const int kLenFieldNumber = 1;
  ::google::protobuf::int32 len() const;
  void set_len(::google::protobuf::int32 value);

  // required int32 protocol = 2;
  bool has_protocol() const;
  void clear_protocol();
  static const int kProtocolFieldNumber = 2;
  ::google::protobuf::int32 protocol() const;
  void set_protocol(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WZRY.MessageHead)
 private:
  void set_has_len();
  void clear_has_len();
  void set_has_protocol();
  void clear_has_protocol();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 len_;
  ::google::protobuf::int32 protocol_;
  friend struct ::protobuf_MessageHeadProto_2eproto::TableStruct;
  friend void ::protobuf_MessageHeadProto_2eproto::InitDefaultsMessageHeadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageHead

// required int32 len = 1;
inline bool MessageHead::has_len() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageHead::set_has_len() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageHead::clear_has_len() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageHead::clear_len() {
  len_ = 0;
  clear_has_len();
}
inline ::google::protobuf::int32 MessageHead::len() const {
  // @@protoc_insertion_point(field_get:WZRY.MessageHead.len)
  return len_;
}
inline void MessageHead::set_len(::google::protobuf::int32 value) {
  set_has_len();
  len_ = value;
  // @@protoc_insertion_point(field_set:WZRY.MessageHead.len)
}

// required int32 protocol = 2;
inline bool MessageHead::has_protocol() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageHead::set_has_protocol() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageHead::clear_has_protocol() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageHead::clear_protocol() {
  protocol_ = 0;
  clear_has_protocol();
}
inline ::google::protobuf::int32 MessageHead::protocol() const {
  // @@protoc_insertion_point(field_get:WZRY.MessageHead.protocol)
  return protocol_;
}
inline void MessageHead::set_protocol(::google::protobuf::int32 value) {
  set_has_protocol();
  protocol_ = value;
  // @@protoc_insertion_point(field_set:WZRY.MessageHead.protocol)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace WZRY

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageHeadProto_2eproto__INCLUDED
